# Generated by Django 4.1.2 on 2023-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
                ("fans", models.CharField(max_length=10000)),
            ],
            options={"ordering": ("name", "fans"),},
        ),
    ]
