# Generated by Django 4.1.2 on 2023-01-17 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coins",
                    models.DecimalField(decimal_places=2, default=100.5, max_digits=15),
                ),
                ("fanscount", models.IntegerField(default=0)),
                ("is_sign_in", models.BooleanField(default=False)),
                (
                    "sign_in_coins",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="User",),
    ]
