# Generated by Django 4.1.2 on 2023-01-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0009_player_following_delete_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="following",
            field=models.ManyToManyField(
                blank=True, default="", related_name="followers", to="User.player"
            ),
        ),
    ]
