# Generated by Django 4.1.2 on 2023-01-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0010_alter_player_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_follow",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="User.player"
            ),
        ),
    ]
