# Generated by Django 4.1.2 on 2023-01-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0011_player_is_follow_alter_player_following"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="is_follow",),
    ]
