# Generated by Django 4.1.2 on 2023-01-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0012_remove_player_is_follow"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="following",),
    ]
