# Generated by Django 4.1.2 on 2023-01-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0014_player_following"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="following",),
    ]
