# Generated by Django 4.1.2 on 2023-01-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0019_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="user_id",),
        migrations.AddField(
            model_name="post",
            name="player",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="User.player",
            ),
        ),
    ]
