# Generated by Django 4.1.2 on 2023-01-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0020_remove_post_user_id_post_player"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-post_date"]},
        ),
        migrations.AddField(
            model_name="post", name="post_date", field=models.DateField(default=""),
        ),
    ]
