# Generated by Django 4.1.2 on 2023-01-18 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0022_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 1, 18, 6, 21, 19, 473053, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
