# Generated by Django 4.1.2 on 2023-01-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0024_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
