# Generated by Django 4.1.2 on 2023-01-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0025_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={"ordering": ["-id"]},),
        migrations.RemoveField(model_name="post", name="post_date",),
    ]
